import type { TemplateConfig } from '../types/template';

const sprintTracker: TemplateConfig = {
  id: 'sprint-tracker',
  name: 'Sprint Tracker',
  description: 'Sprint task table, velocity line chart, and status badge cards',
  components: [
    {
      id: 'badge-1',
      type: 'StatusBadge',
      label: 'To Do',
      style: {
        backgroundColor: '#1c1c26',
        textColor: '#fdcb6e',
        fontFamily: 'Inter',
        fontSize: 13,
        borderRadius: 10,
        borderColor: '#2a2a3a',
        borderWidth: 1,
        padding: 16,
      },
      data: {
        fieldName: 'todo_count',
        mockValue: '8 Tasks',
        dbBinding: 'sprints.todo_count',
        refreshOn: 'onLoad',
      },
    },
    {
      id: 'badge-2',
      type: 'StatusBadge',
      label: 'In Progress',
      style: {
        backgroundColor: '#1c1c26',
        textColor: '#6c5ce7',
        fontFamily: 'Inter',
        fontSize: 13,
        borderRadius: 10,
        borderColor: '#2a2a3a',
        borderWidth: 1,
        padding: 16,
      },
      data: {
        fieldName: 'in_progress_count',
        mockValue: '5 Tasks',
        dbBinding: 'sprints.in_progress_count',
        refreshOn: 'onLoad',
      },
    },
    {
      id: 'badge-3',
      type: 'StatusBadge',
      label: 'Done',
      style: {
        backgroundColor: '#1c1c26',
        textColor: '#00b894',
        fontFamily: 'Inter',
        fontSize: 13,
        borderRadius: 10,
        borderColor: '#2a2a3a',
        borderWidth: 1,
        padding: 16,
      },
      data: {
        fieldName: 'done_count',
        mockValue: '14 Tasks',
        dbBinding: 'sprints.done_count',
        refreshOn: 'onLoad',
      },
    },
    {
      id: 'badge-4',
      type: 'StatusBadge',
      label: 'Blocked',
      style: {
        backgroundColor: '#1c1c26',
        textColor: '#ff6b6b',
        fontFamily: 'Inter',
        fontSize: 13,
        borderRadius: 10,
        borderColor: '#2a2a3a',
        borderWidth: 1,
        padding: 16,
      },
      data: {
        fieldName: 'blocked_count',
        mockValue: '2 Tasks',
        dbBinding: 'sprints.blocked_count',
        refreshOn: 'onLoad',
      },
    },
    {
      id: 'chart-sprint',
      type: 'LineChart',
      label: 'Sprint Velocity',
      style: {
        backgroundColor: '#1c1c26',
        textColor: '#f0f0f5',
        fontFamily: 'Inter',
        fontSize: 14,
        borderRadius: 10,
        borderColor: '#2a2a3a',
        borderWidth: 1,
        padding: 20,
      },
      data: {
        series: [
          { name: 'Planned', fieldKey: 'planned' },
          { name: 'Completed', fieldKey: 'completed' },
        ],
        mockValue: [
          { sprint: 'Sprint 1', planned: 20, completed: 18 },
          { sprint: 'Sprint 2', planned: 22, completed: 21 },
          { sprint: 'Sprint 3', planned: 25, completed: 20 },
          { sprint: 'Sprint 4', planned: 23, completed: 23 },
          { sprint: 'Sprint 5', planned: 28, completed: 24 },
          { sprint: 'Sprint 6', planned: 26, completed: 25 },
        ],
        dbBinding: 'sprints.velocity',
        refreshOn: 'onLoad',
      },
    },
    {
      id: 'table-sprint',
      type: 'Table',
      label: 'Sprint Tasks',
      style: {
        backgroundColor: '#1c1c26',
        textColor: '#f0f0f5',
        fontFamily: 'Inter',
        fontSize: 13,
        borderRadius: 10,
        borderColor: '#2a2a3a',
        borderWidth: 1,
        padding: 0,
      },
      data: {
        columns: [
          { name: 'Task', fieldKey: 'task' },
          { name: 'Assignee', fieldKey: 'assignee' },
          { name: 'Points', fieldKey: 'points' },
          { name: 'Status', fieldKey: 'status' },
        ],
        mockValue: [
          { task: 'Setup auth flow', assignee: 'Alice', points: 5, status: 'Done' },
          { task: 'API integration', assignee: 'Bob', points: 8, status: 'In Progress' },
          { task: 'Dashboard charts', assignee: 'Charlie', points: 3, status: 'In Progress' },
          { task: 'Unit tests', assignee: 'Diana', points: 5, status: 'To Do' },
          { task: 'Code review', assignee: 'Eve', points: 2, status: 'Blocked' },
          { task: 'Deploy staging', assignee: 'Alice', points: 3, status: 'To Do' },
        ],
        dbBinding: 'sprints.tasks',
        refreshOn: 'onLoad',
      },
    },
  ],
};

export default sprintTracker;
