import type { TemplateConfig } from '../types/template';

const emeraldGrove: TemplateConfig = {
  id: 'emerald-grove',
  name: 'Emerald Grove',
  description: 'Lush emerald green with golden accents and natural tones',
  components: [
    {
      id: 'top-banner',
      type: 'Container',
      label: 'Top Banner',
      layout: { x: 0, y: 0, w: 12, h: 2 },
      style: {
        backgroundColor: '#1a3a2e',
        borderColor: '#d4af37',
        borderWidth: 0,
        borderRadius: 0,
        padding: 16,
        boxShadow: '0 4px 12px rgba(212, 175, 55, 0.15)',
      },
      data: {},
    },
    {
      id: 'header-title',
      type: 'Text',
      label: 'Dashboard Title',
      layout: { x: 0, y: 0, w: 12, h: 2 },
      style: {
        fontSize: 28,
        fontWeight: 700,
        textColor: '#d4af37',
        backgroundColor: 'transparent',
      },
      data: { mockValue: 'Growth Dashboard' },
    },
    {
      id: 'stat-sales',
      type: 'StatCard',
      label: 'Total Sales',
      layout: { x: 0, y: 2, w: 3, h: 5 },
      style: {
        backgroundColor: '#0fdf64',
        borderLeftColor: '#0fdf64',
        borderLeftWidth: 4,
        borderRadius: 14,
        padding: 22,
        textColor: '#ffffff',
        metricFontSize: 32,
        labelFontSize: 13,
        boxShadow: '0 4px 12px rgba(15, 223, 100, 0.2), 0 12px 32px rgba(15, 223, 100, 0.12)',
        backgroundGradient: {
          enabled: true,
          direction: 135,
          stops: [
            { color: '#0fdf64', position: 0 },
            { color: '#06b347', position: 100 },
          ],
        },
      },
      data: { mockValue: '$5.8M' },
    },
    {
      id: 'stat-profit',
      type: 'StatCard',
      label: 'Net Profit',
      layout: { x: 3, y: 2, w: 3, h: 5 },
      style: {
        backgroundColor: '#d4af37',
        borderLeftColor: '#d4af37',
        borderLeftWidth: 4,
        borderRadius: 14,
        padding: 22,
        textColor: '#1a3a2e',
        metricFontSize: 32,
        labelFontSize: 13,
        boxShadow: '0 4px 12px rgba(212, 175, 55, 0.2), 0 12px 32px rgba(212, 175, 55, 0.12)',
        backgroundGradient: {
          enabled: true,
          direction: 135,
          stops: [
            { color: '#d4af37', position: 0 },
            { color: '#b8941a', position: 100 },
          ],
        },
      },
      data: { mockValue: '$1.2M' },
    },
    {
      id: 'stat-conversion',
      type: 'StatCard',
      label: 'Conversion',
      layout: { x: 6, y: 2, w: 3, h: 5 },
      style: {
        backgroundColor: '#f0f9e8',
        borderLeftColor: '#0fdf64',
        borderLeftWidth: 4,
        borderRadius: 14,
        padding: 22,
        textColor: '#1a3a2e',
        metricFontSize: 32,
        labelFontSize: 13,
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 12px rgba(15, 23, 42, 0.06)',
      },
      data: { mockValue: '12.4%' },
    },
    {
      id: 'stat-visitors',
      type: 'StatCard',
      label: 'Visitors',
      layout: { x: 9, y: 2, w: 3, h: 5 },
      style: {
        backgroundColor: '#f0f9e8',
        borderLeftColor: '#0fdf64',
        borderLeftWidth: 4,
        borderRadius: 14,
        padding: 22,
        textColor: '#1a3a2e',
        metricFontSize: 32,
        labelFontSize: 13,
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 12px rgba(15, 23, 42, 0.06)',
      },
      data: { mockValue: '54.3K' },
    },
    {
      id: 'chart-revenue-trend',
      type: 'LineChart',
      label: 'Revenue Trend (6 Months)',
      layout: { x: 0, y: 7, w: 6, h: 8 },
      style: {
        backgroundColor: '#f0f9e8',
        borderColor: '#dcfce7',
        borderRadius: 12,
        padding: 18,
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 12px rgba(15, 23, 42, 0.06)',
      },
      data: {
        showGrid: true,
        showLegend: true,
        smooth: true,
      },
    },
    {
      id: 'chart-breakdown',
      type: 'BarChart',
      label: 'Sales Breakdown by Region',
      layout: { x: 6, y: 7, w: 6, h: 8 },
      style: {
        backgroundColor: '#f0f9e8',
        borderColor: '#dcfce7',
        borderRadius: 12,
        padding: 18,
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 12px rgba(15, 23, 42, 0.06)',
      },
      data: {
        showGrid: true,
        showLegend: true,
      },
    },
    {
      id: 'insights-container',
      type: 'Container',
      label: 'Key Insights',
      layout: { x: 0, y: 15, w: 12, h: 6 },
      style: {
        backgroundColor: '#f7fdf9',
        borderColor: '#dcfce7',
        borderWidth: 1,
        borderRadius: 12,
        padding: 20,
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 12px rgba(15, 23, 42, 0.06)',
      },
      data: {},
    },
    {
      id: 'insight-title',
      type: 'Text',
      label: 'Insights Title',
      layout: { x: 0, y: 15, w: 12, h: 1 },
      style: {
        fontSize: 18,
        fontWeight: 700,
        textColor: '#1a3a2e',
        backgroundColor: 'transparent',
      },
      data: { mockValue: '📊 Key Performance Indicators' },
    },
  ],
  queries: [],
  canvasStyle: {
    backgroundColor: '#152e26',
    backgroundGradient: {
      enabled: true,
      direction: 135,
      stops: [
        { color: '#0f2417', position: 0 },
        { color: '#1a3a2e', position: 100 },
      ],
    },
  },
};

export default emeraldGrove;
