import type { TemplateConfig } from '../types/template';

const majesticMaroon: TemplateConfig = {
  id: 'majestic-maroon',
  name: 'Majestic Maroon',
  description: 'Elegant dark maroon dashboard with coral accents and premium styling',
  components: [
    {
      id: 'navbar-1',
      type: 'Container',
      label: 'Navigation Bar',
      layout: { x: 0, y: 0, w: 12, h: 2 },
      style: {
        backgroundColor: '#1a0f0f',
        borderColor: '#ff6b54',
        borderWidth: 0,
        borderRadius: 0,
        padding: 16,
        boxShadow: '0 4px 12px rgba(255, 107, 84, 0.15)',
      },
      data: {},
    },
    {
      id: 'title-text',
      type: 'Text',
      label: 'Dashboard Title',
      layout: { x: 0, y: 0, w: 6, h: 2 },
      style: {
        fontSize: 28,
        fontWeight: 700,
        textColor: '#ffffff',
        backgroundColor: 'transparent',
      },
      data: { mockValue: 'Analytics Hub' },
    },
    {
      id: 'stat-revenue',
      type: 'StatCard',
      label: 'Total Revenue',
      layout: { x: 0, y: 2, w: 3, h: 5 },
      style: {
        backgroundColor: '#ff6b54',
        borderLeftColor: '#ff6b54',
        borderLeftWidth: 4,
        borderRadius: 14,
        padding: 22,
        textColor: '#ffffff',
        metricFontSize: 32,
        labelFontSize: 13,
        boxShadow: '0 4px 12px rgba(255, 107, 84, 0.2), 0 12px 32px rgba(255, 107, 84, 0.12)',
        backgroundGradient: {
          enabled: true,
          direction: 135,
          stops: [
            { color: '#ff6b54', position: 0 },
            { color: '#ff4d32', position: 100 },
          ],
        },
      },
      data: { mockValue: '$2.4M' },
    },
    {
      id: 'stat-orders',
      type: 'StatCard',
      label: 'Total Orders',
      layout: { x: 3, y: 2, w: 3, h: 5 },
      style: {
        backgroundColor: '#e8f4f8',
        borderLeftColor: '#00a8cc',
        borderLeftWidth: 4,
        borderRadius: 14,
        padding: 22,
        textColor: '#0f172a',
        metricFontSize: 32,
        labelFontSize: 13,
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 12px rgba(15, 23, 42, 0.06)',
      },
      data: { mockValue: '3,847' },
    },
    {
      id: 'stat-growth',
      type: 'StatCard',
      label: 'Growth Rate',
      layout: { x: 6, y: 2, w: 3, h: 5 },
      style: {
        backgroundColor: '#f0f9e8',
        borderLeftColor: '#4ade80',
        borderLeftWidth: 4,
        borderRadius: 14,
        padding: 22,
        textColor: '#0f172a',
        metricFontSize: 32,
        labelFontSize: 13,
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 12px rgba(15, 23, 42, 0.06)',
      },
      data: { mockValue: '23.5%' },
    },
    {
      id: 'stat-customers',
      type: 'StatCard',
      label: 'Active Users',
      layout: { x: 9, y: 2, w: 3, h: 5 },
      style: {
        backgroundColor: '#fff5e8',
        borderLeftColor: '#f59e0b',
        borderLeftWidth: 4,
        borderRadius: 14,
        padding: 22,
        textColor: '#0f172a',
        metricFontSize: 32,
        labelFontSize: 13,
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 12px rgba(15, 23, 42, 0.06)',
      },
      data: { mockValue: '8,234' },
    },
    {
      id: 'chart-revenue',
      type: 'LineChart',
      label: 'Revenue Trend',
      layout: { x: 0, y: 7, w: 6, h: 8 },
      style: {
        backgroundColor: '#e8f4f8',
        borderColor: '#b0e0e6',
        borderRadius: 12,
        padding: 18,
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 12px rgba(15, 23, 42, 0.06)',
      },
      data: {
        showGrid: true,
        showLegend: true,
        smooth: true,
      },
    },
    {
      id: 'chart-categories',
      type: 'BarChart',
      label: 'Sales by Category',
      layout: { x: 6, y: 7, w: 6, h: 8 },
      style: {
        backgroundColor: '#fff5e8',
        borderColor: '#ffe8c2',
        borderRadius: 12,
        padding: 18,
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 12px rgba(15, 23, 42, 0.06)',
      },
      data: {
        showGrid: true,
        showLegend: true,
      },
    },
    {
      id: 'table-sales',
      type: 'Table',
      label: 'Recent Sales',
      layout: { x: 0, y: 15, w: 12, h: 6 },
      style: {
        backgroundColor: '#f8fafc',
        borderColor: '#e2e8f0',
        borderRadius: 12,
        padding: 0,
        stripeRows: true,
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 12px rgba(15, 23, 42, 0.06)',
      },
      data: {
        searchable: true,
        pagination: true,
        columns: [
          { name: 'Order ID', fieldKey: 'id' },
          { name: 'Customer', fieldKey: 'customer' },
          { name: 'Amount', fieldKey: 'amount' },
          { name: 'Status', fieldKey: 'status' },
          { name: 'Date', fieldKey: 'date' },
        ],
      },
    },
  ],
  queries: [],
  canvasStyle: {
    backgroundColor: '#2a1515',
    backgroundGradient: {
      enabled: true,
      direction: 135,
      stops: [
        { color: '#1a0f0f', position: 0 },
        { color: '#3d1f1f', position: 100 },
      ],
    },
  },
};

export default majesticMaroon;
