import type { TemplateConfig } from '../types/template';

const midnightIndigo: TemplateConfig = {
  id: 'midnight-indigo',
  name: 'Midnight Indigo',
  description: 'Deep indigo dark theme with golden and cyan accents',
  components: [
    {
      id: 'navbar-dark',
      type: 'Container',
      label: 'Navigation',
      layout: { x: 0, y: 0, w: 12, h: 2 },
      style: {
        backgroundColor: '#0e0621',
        borderColor: '#6366f1',
        borderWidth: 0,
        borderRadius: 0,
        padding: 16,
        boxShadow: '0 4px 12px rgba(99, 102, 241, 0.1)',
      },
      data: {},
    },
    {
      id: 'nav-title',
      type: 'Text',
      label: 'Nav Title',
      layout: { x: 0, y: 0, w: 8, h: 2 },
      style: {
        fontSize: 26,
        fontWeight: 700,
        textColor: '#6366f1',
        backgroundColor: 'transparent',
      },
      data: { mockValue: 'Premium Analytics' },
    },
    {
      id: 'badge-premium',
      type: 'StatusBadge',
      label: 'Premium',
      layout: { x: 10, y: 0, w: 2, h: 2 },
      style: {
        backgroundColor: '#6366f1',
        borderColor: '#6366f1',
        borderRadius: 8,
        padding: 8,
        textColor: '#ffffff',
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 12px rgba(15, 23, 42, 0.06)',
      },
      data: { mockValue: '⭐ Pro' },
    },
    {
      id: 'card-revenue-hero',
      type: 'StatCard',
      label: 'Monthly Revenue',
      layout: { x: 0, y: 2, w: 4, h: 6 },
      style: {
        backgroundColor: '#1e1b4b',
        borderLeftColor: '#6366f1',
        borderLeftWidth: 4,
        borderRadius: 14,
        padding: 22,
        textColor: '#fafafa',
        metricFontSize: 36,
        labelFontSize: 13,
        boxShadow: '0 4px 16px rgba(99, 102, 241, 0.2), 0 16px 36px rgba(99, 102, 241, 0.12)',
        backgroundGradient: {
          enabled: true,
          direction: 135,
          stops: [
            { color: '#1e1b4b', position: 0 },
            { color: '#312e81', position: 100 },
          ],
        },
      },
      data: { mockValue: '$3.2M' },
    },
    {
      id: 'card-gold',
      type: 'StatCard',
      label: 'Premium Subscriptions',
      layout: { x: 4, y: 2, w: 4, h: 6 },
      style: {
        backgroundColor: '#fbbf24',
        borderLeftColor: '#fbbf24',
        borderLeftWidth: 4,
        borderRadius: 14,
        padding: 22,
        textColor: '#1f2937',
        metricFontSize: 36,
        labelFontSize: 13,
        boxShadow: '0 4px 12px rgba(251, 191, 36, 0.2), 0 12px 32px rgba(251, 191, 36, 0.12)',
        backgroundGradient: {
          enabled: true,
          direction: 135,
          stops: [
            { color: '#fbbf24', position: 0 },
            { color: '#f59e0b', position: 100 },
          ],
        },
      },
      data: { mockValue: '4,289' },
    },
    {
      id: 'card-churn',
      type: 'StatCard',
      label: 'Churn Rate',
      layout: { x: 8, y: 2, w: 4, h: 6 },
      style: {
        backgroundColor: '#0f0f12',
        borderLeftColor: '#06b6d4',
        borderLeftWidth: 4,
        borderRadius: 14,
        padding: 22,
        textColor: '#fafafa',
        metricFontSize: 36,
        labelFontSize: 13,
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 12px rgba(15, 23, 42, 0.06)',
      },
      data: { mockValue: '2.1%' },
    },
    {
      id: 'chart-financial',
      type: 'LineChart',
      label: 'Financial Metrics (YTD)',
      layout: { x: 0, y: 8, w: 6, h: 8 },
      style: {
        backgroundColor: '#0c0c14',
        borderColor: '#1e2d42',
        borderRadius: 12,
        padding: 18,
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 12px rgba(15, 23, 42, 0.06)',
      },
      data: {
        showGrid: true,
        showLegend: true,
        smooth: true,
      },
    },
    {
      id: 'chart-segments',
      type: 'BarChart',
      label: 'Revenue by Segment',
      layout: { x: 6, y: 8, w: 6, h: 8 },
      style: {
        backgroundColor: '#0c0c14',
        borderColor: '#1e2d42',
        borderRadius: 12,
        padding: 18,
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 12px rgba(15, 23, 42, 0.06)',
      },
      data: {
        showGrid: true,
        showLegend: true,
      },
    },
    {
      id: 'table-transactions',
      type: 'Table',
      label: 'Recent Transactions',
      layout: { x: 0, y: 16, w: 12, h: 5 },
      style: {
        backgroundColor: '#09090b',
        borderColor: '#27272a',
        borderRadius: 12,
        padding: 0,
        stripeRows: true,
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 12px rgba(15, 23, 42, 0.06)',
      },
      data: {
        searchable: true,
        pagination: true,
        columns: [
          { name: 'Transaction ID', fieldKey: 'id' },
          { name: 'Customer', fieldKey: 'customer' },
          { name: 'Amount', fieldKey: 'amount' },
          { name: 'Type', fieldKey: 'type' },
          { name: 'Timestamp', fieldKey: 'timestamp' },
        ],
      },
    },
  ],
  queries: [],
  canvasStyle: {
    backgroundColor: '#05030a',
    backgroundGradient: {
      enabled: true,
      direction: 135,
      stops: [
        { color: '#03020a', position: 0 },
        { color: '#0e0621', position: 100 },
      ],
    },
  },
};

export default midnightIndigo;
