import type { TemplateConfig } from '../types/template';

const sunsetBlaze: TemplateConfig = {
  id: 'sunset-blaze',
  name: 'Sunset Blaze',
  description: 'Warm orange and amber sunset theme with cream accents',
  components: [
    {
      id: 'header-sunset',
      type: 'Container',
      label: 'Header',
      layout: { x: 0, y: 0, w: 12, h: 2 },
      style: {
        backgroundColor: '#7c2d12',
        borderColor: '#fb923c',
        borderWidth: 0,
        borderRadius: 0,
        padding: 16,
        boxShadow: '0 4px 12px rgba(251, 146, 60, 0.15)',
      },
      data: {},
    },
    {
      id: 'header-text-main',
      type: 'Text',
      label: 'Main Title',
      layout: { x: 0, y: 0, w: 12, h: 2 },
      style: {
        fontSize: 28,
        fontWeight: 700,
        textColor: '#fef3c7',
        backgroundColor: 'transparent',
      },
      data: { mockValue: 'Business Intelligence Center' },
    },
    {
      id: 'stat-primary-metric',
      type: 'StatCard',
      label: 'Total Earnings',
      layout: { x: 0, y: 2, w: 3, h: 5 },
      style: {
        backgroundColor: '#fb923c',
        borderLeftColor: '#fb923c',
        borderLeftWidth: 4,
        borderRadius: 14,
        padding: 22,
        textColor: '#fffbeb',
        metricFontSize: 32,
        labelFontSize: 13,
        boxShadow: '0 4px 12px rgba(251, 146, 60, 0.2), 0 12px 32px rgba(251, 146, 60, 0.12)',
        backgroundGradient: {
          enabled: true,
          direction: 135,
          stops: [
            { color: '#fb923c', position: 0 },
            { color: '#ea580c', position: 100 },
          ],
        },
      },
      data: { mockValue: '$847K' },
    },
    {
      id: 'stat-engagement',
      type: 'StatCard',
      label: 'Engagement Score',
      layout: { x: 3, y: 2, w: 3, h: 5 },
      style: {
        backgroundColor: '#fffbeb',
        borderLeftColor: '#b45309',
        borderLeftWidth: 4,
        borderRadius: 14,
        padding: 22,
        textColor: '#292524',
        metricFontSize: 32,
        labelFontSize: 13,
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 12px rgba(15, 23, 42, 0.06)',
      },
      data: { mockValue: '87.3%' },
    },
    {
      id: 'stat-active-users',
      type: 'StatCard',
      label: 'Active Users',
      layout: { x: 6, y: 2, w: 3, h: 5 },
      style: {
        backgroundColor: '#fffbeb',
        borderLeftColor: '#fb923c',
        borderLeftWidth: 4,
        borderRadius: 14,
        padding: 22,
        textColor: '#292524',
        metricFontSize: 32,
        labelFontSize: 13,
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 12px rgba(15, 23, 42, 0.06)',
      },
      data: { mockValue: '12.5K' },
    },
    {
      id: 'stat-growth',
      type: 'StatCard',
      label: 'Month Growth',
      layout: { x: 9, y: 2, w: 3, h: 5 },
      style: {
        backgroundColor: '#fffbeb',
        borderLeftColor: '#ea580c',
        borderLeftWidth: 4,
        borderRadius: 14,
        padding: 22,
        textColor: '#292524',
        metricFontSize: 32,
        labelFontSize: 13,
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 12px rgba(15, 23, 42, 0.06)',
      },
      data: { mockValue: '34.2%' },
    },
    {
      id: 'chart-earnings-trend',
      type: 'LineChart',
      label: 'Earnings Trend (Last 12 Months)',
      layout: { x: 0, y: 7, w: 6, h: 8 },
      style: {
        backgroundColor: '#fef3c7',
        borderColor: '#fef9c3',
        borderRadius: 12,
        padding: 18,
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 12px rgba(15, 23, 42, 0.06)',
      },
      data: {
        showGrid: true,
        showLegend: true,
        smooth: true,
      },
    },
    {
      id: 'chart-category-breakdown',
      type: 'BarChart',
      label: 'Performance by Category',
      layout: { x: 6, y: 7, w: 6, h: 8 },
      style: {
        backgroundColor: '#fef3c7',
        borderColor: '#fef9c3',
        borderRadius: 12,
        padding: 18,
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 12px rgba(15, 23, 42, 0.06)',
      },
      data: {
        showGrid: true,
        showLegend: true,
      },
    },
    {
      id: 'insights-box',
      type: 'Container',
      label: 'Quick Insights',
      layout: { x: 0, y: 15, w: 12, h: 6 },
      style: {
        backgroundColor: '#fffbeb',
        borderColor: '#fde68a',
        borderWidth: 1,
        borderRadius: 12,
        padding: 20,
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 12px rgba(15, 23, 42, 0.06)',
      },
      data: {},
    },
    {
      id: 'insights-header',
      type: 'Text',
      label: 'Insights Header',
      layout: { x: 0, y: 15, w: 12, h: 1 },
      style: {
        fontSize: 18,
        fontWeight: 700,
        textColor: '#7c2d12',
        backgroundColor: 'transparent',
      },
      data: { mockValue: '🔥 Hot Trends & Insights' },
    },
    {
      id: 'insight-detail',
      type: 'Text',
      label: 'Insight Details',
      layout: { x: 0, y: 16, w: 12, h: 4 },
      style: {
        fontSize: 14,
        textColor: '#78716c',
        backgroundColor: 'transparent',
        lineHeight: 1.6,
      },
      data: { mockValue: '• Revenue is up 28% compared to last month\n• Top performing products: Electronics, Home Goods\n• Peak engagement time: 6-9 PM EST\n• Customer retention rate: 94.2% (↑5.3%)' },
    },
  ],
  queries: [],
  canvasStyle: {
    backgroundColor: '#fefce8',
    backgroundGradient: {
      enabled: true,
      direction: 135,
      stops: [
        { color: '#fffbeb', position: 0 },
        { color: '#fef3c7', position: 100 },
      ],
    },
  },
};

export default sunsetBlaze;
