import type { TemplateConfig } from '../types/template';

// Resource is looked up by name in the imported resources.
// User imported the mock Express API with this name.
const RESOURCE = 'Demo Backend';

const demoBackendSuite: TemplateConfig = {
  id: 'demo-backend-suite',
  name: 'Demo Backend Suite',
  description:
    'Premium dark-gradient dashboard wired to the Demo Backend mock API. KPIs, revenue chart, users/orders/products tables, activity logs, node graph, and global search — all live.',
  components: [
    // ─── Navigation Bar ──────────────────────────────────────────────────
    {
      id: 'navbar',
      type: 'Container',
      label: 'Navigation Bar',
      layout: { x: 0, y: 0, w: 12, h: 2 },
      style: {
        backgroundColor: '#0d1424',
        borderColor: '#3b82f6',
        borderWidth: 0,
        borderRadius: 0,
        padding: 16,
        boxShadow: '0 4px 12px rgba(59, 130, 246, 0.18)',
      },
      data: {},
    },
    {
      id: 'navbar-title',
      type: 'Text',
      label: 'Dashboard Title',
      layout: { x: 0, y: 0, w: 8, h: 2 },
      style: {
        fontSize: 26,
        fontWeight: 700,
        textColor: '#f8fafc',
        backgroundColor: 'transparent',
      },
      data: { mockValue: '🚀 Demo Backend Analytics' },
    },
    {
      id: 'navbar-status',
      type: 'StatusBadge',
      label: 'API Status',
      layout: { x: 10, y: 0, w: 2, h: 2 },
      style: {
        backgroundColor: '#0c1f2e',
        borderColor: '#10b981',
        borderRadius: 8,
        padding: 8,
        textColor: '#10b981',
      },
      data: { mockValue: '● API Live' },
    },

    // ─── KPI Row ─────────────────────────────────────────────────────────
    {
      id: 'kpi-revenue',
      type: 'StatCard',
      label: 'Total Revenue',
      layout: { x: 0, y: 2, w: 3, h: 4 },
      style: {
        backgroundColor: '#1e3a8a',
        borderLeftColor: '#3b82f6',
        borderLeftWidth: 4,
        borderRadius: 14,
        padding: 22,
        textColor: '#ffffff',
        metricFontSize: 30,
        labelFontSize: 12,
        boxShadow: '0 4px 12px rgba(59, 130, 246, 0.25)',
        backgroundGradient: {
          enabled: true,
          direction: 135,
          stops: [
            { color: '#1e3a8a', position: 0 },
            { color: '#3b82f6', position: 100 },
          ],
        },
      },
      data: {
        mockValue: '0',
        prefix: '$',
        formatter: 'Compact',
        trend: '+12%',
        trendType: 'positive',
        dbBinding: '{{queries.get-stats.data.total_revenue}}',
      },
    },
    {
      id: 'kpi-orders',
      type: 'StatCard',
      label: 'Total Orders',
      layout: { x: 3, y: 2, w: 3, h: 4 },
      style: {
        backgroundColor: '#581c87',
        borderLeftColor: '#a855f7',
        borderLeftWidth: 4,
        borderRadius: 14,
        padding: 22,
        textColor: '#ffffff',
        metricFontSize: 30,
        labelFontSize: 12,
        boxShadow: '0 4px 12px rgba(168, 85, 247, 0.25)',
        backgroundGradient: {
          enabled: true,
          direction: 135,
          stops: [
            { color: '#581c87', position: 0 },
            { color: '#a855f7', position: 100 },
          ],
        },
      },
      data: {
        mockValue: '0',
        formatter: 'None',
        trend: '+8%',
        trendType: 'positive',
        dbBinding: '{{queries.get-stats.data.total_orders}}',
      },
    },
    {
      id: 'kpi-users',
      type: 'StatCard',
      label: 'Active Users',
      layout: { x: 6, y: 2, w: 3, h: 4 },
      style: {
        backgroundColor: '#7c2d12',
        borderLeftColor: '#f97316',
        borderLeftWidth: 4,
        borderRadius: 14,
        padding: 22,
        textColor: '#ffffff',
        metricFontSize: 30,
        labelFontSize: 12,
        boxShadow: '0 4px 12px rgba(249, 115, 22, 0.25)',
        backgroundGradient: {
          enabled: true,
          direction: 135,
          stops: [
            { color: '#7c2d12', position: 0 },
            { color: '#f97316', position: 100 },
          ],
        },
      },
      data: {
        mockValue: '0',
        formatter: 'None',
        trend: '+5%',
        trendType: 'positive',
        dbBinding: '{{queries.get-stats.data.active_users}}',
      },
    },
    {
      id: 'kpi-products',
      type: 'StatCard',
      label: 'Pending Orders',
      layout: { x: 9, y: 2, w: 3, h: 4 },
      style: {
        backgroundColor: '#134e4a',
        borderLeftColor: '#14b8a6',
        borderLeftWidth: 4,
        borderRadius: 14,
        padding: 22,
        textColor: '#ffffff',
        metricFontSize: 30,
        labelFontSize: 12,
        boxShadow: '0 4px 12px rgba(20, 184, 166, 0.25)',
        backgroundGradient: {
          enabled: true,
          direction: 135,
          stops: [
            { color: '#134e4a', position: 0 },
            { color: '#14b8a6', position: 100 },
          ],
        },
      },
      data: {
        mockValue: '0',
        formatter: 'None',
        trend: '-2',
        trendType: 'negative',
        dbBinding: '{{queries.get-stats.data.pending_orders}}',
      },
    },

    // ─── Section: Revenue Chart + Trend Line ────────────────────────────
    {
      id: 'section-analytics',
      type: 'Text',
      label: 'Analytics Section',
      layout: { x: 0, y: 6, w: 12, h: 1 },
      style: {
        fontSize: 14,
        fontWeight: 600,
        textColor: '#94a3b8',
        backgroundColor: 'transparent',
        textTransform: 'uppercase',
        letterSpacing: 2,
      },
      data: { mockValue: '📈  Revenue Analytics' },
    },
    {
      id: 'chart-revenue-bar',
      type: 'BarChart',
      label: 'Monthly Revenue',
      layout: { x: 0, y: 7, w: 7, h: 8 },
      style: {
        backgroundColor: '#111c2e',
        borderColor: '#1e293b',
        borderWidth: 1,
        borderRadius: 12,
        padding: 16,
        boxShadow: '0 4px 12px rgba(59, 130, 246, 0.12)',
        seriesColors: ['#3b82f6', '#8b5cf6', '#06b6d4'],
        gridColor: '#1e293b',
        axisColor: '#64748b',
        textColor: '#cbd5e1',
      },
      data: {
        showGrid: true,
        showLegend: true,
        showXAxis: true,
        showYAxis: true,
        xField: 'date',
        yField: 'revenue',
        colorScheme: 'Blue',
        orientation: 'Vertical',
        barRadius: 6,
        showDataLabels: false,
        dbBinding: '{{queries.get-revenue-chart.data}}',
        mockValue: [
          { date: '2025-04-21', revenue: 1240 },
          { date: '2025-04-22', revenue: 980 },
          { date: '2025-04-23', revenue: 1580 },
          { date: '2025-04-24', revenue: 720 },
          { date: '2025-04-25', revenue: 2100 },
          { date: '2025-04-26', revenue: 1860 },
        ],
      },
    },
    {
      id: 'chart-revenue-trend',
      type: 'LineChart',
      label: 'Revenue Trend',
      layout: { x: 7, y: 7, w: 5, h: 8 },
      style: {
        backgroundColor: '#111c2e',
        borderColor: '#1e293b',
        borderWidth: 1,
        borderRadius: 12,
        padding: 16,
        boxShadow: '0 4px 12px rgba(168, 85, 247, 0.12)',
        seriesColors: ['#a855f7'],
        gridColor: '#1e293b',
        axisColor: '#64748b',
        textColor: '#cbd5e1',
        lineWidth: 3,
      },
      data: {
        showGrid: true,
        showLegend: false,
        showXAxis: true,
        showYAxis: true,
        smooth: true,
        showDots: true,
        fillArea: true,
        xField: 'date',
        yField: 'revenue',
        colorScheme: 'Multi',
        dbBinding: '{{queries.get-revenue-chart.data}}',
        mockValue: [
          { date: '2025-04-21', revenue: 1240 },
          { date: '2025-04-22', revenue: 980 },
          { date: '2025-04-23', revenue: 1580 },
          { date: '2025-04-24', revenue: 720 },
          { date: '2025-04-25', revenue: 2100 },
          { date: '2025-04-26', revenue: 1860 },
        ],
      },
    },

    // ─── Section: Users + Orders Tables ─────────────────────────────────
    {
      id: 'section-management',
      type: 'Text',
      label: 'Management Section',
      layout: { x: 0, y: 15, w: 12, h: 1 },
      style: {
        fontSize: 14,
        fontWeight: 600,
        textColor: '#94a3b8',
        backgroundColor: 'transparent',
        textTransform: 'uppercase',
        letterSpacing: 2,
      },
      data: { mockValue: '👥  Users & Orders Management' },
    },
    {
      id: 'table-users',
      type: 'Table',
      label: 'Users',
      layout: { x: 0, y: 16, w: 6, h: 8 },
      style: {
        backgroundColor: '#0d1424',
        borderColor: '#1e293b',
        headerBackgroundColor: '#111c2e',
        textColor: '#e2e8f0',
        borderRadius: 12,
        padding: 0,
        stripeRows: true,
        rowAlternateColor: '#101a2c',
        searchBarBackground: '#111c2e',
        searchBarTextColor: '#cbd5e1',
        searchBarBorderColor: '#1e293b',
      },
      data: {
        searchable: true,
        pagination: true,
        columns: [
          { name: 'ID',      fieldKey: 'id' },
          { name: 'Name',    fieldKey: 'name' },
          { name: 'Email',   fieldKey: 'email' },
          { name: 'Role',    fieldKey: 'role' },
          { name: 'Status',  fieldKey: 'status' },
          { name: 'Revenue', fieldKey: 'revenue' },
        ],
        dbBinding: '{{queries.get-users.data.data}}',
        mockValue: [],
      },
    },
    {
      id: 'table-orders',
      type: 'Table',
      label: 'Orders',
      layout: { x: 6, y: 16, w: 6, h: 8 },
      style: {
        backgroundColor: '#0d1424',
        borderColor: '#1e293b',
        headerBackgroundColor: '#111c2e',
        textColor: '#e2e8f0',
        borderRadius: 12,
        padding: 0,
        stripeRows: true,
        rowAlternateColor: '#101a2c',
        searchBarBackground: '#111c2e',
        searchBarTextColor: '#cbd5e1',
        searchBarBorderColor: '#1e293b',
      },
      data: {
        searchable: true,
        pagination: true,
        columns: [
          { name: 'Order ID', fieldKey: 'id' },
          { name: 'User ID',  fieldKey: 'user_id' },
          { name: 'Product',  fieldKey: 'product' },
          { name: 'Amount',   fieldKey: 'amount' },
          { name: 'Status',   fieldKey: 'status' },
          { name: 'Created',  fieldKey: 'created_at' },
        ],
        dbBinding: '{{queries.get-orders.data.data}}',
        mockValue: [],
      },
    },

    // ─── Section: Products + Relationship Graph ─────────────────────────
    {
      id: 'section-catalog',
      type: 'Text',
      label: 'Catalog Section',
      layout: { x: 0, y: 24, w: 12, h: 1 },
      style: {
        fontSize: 14,
        fontWeight: 600,
        textColor: '#94a3b8',
        backgroundColor: 'transparent',
        textTransform: 'uppercase',
        letterSpacing: 2,
      },
      data: { mockValue: '📦  Catalog & Resource Graph' },
    },
    {
      id: 'table-products',
      type: 'Table',
      label: 'Products Inventory',
      layout: { x: 0, y: 25, w: 8, h: 8 },
      style: {
        backgroundColor: '#0d1424',
        borderColor: '#1e293b',
        headerBackgroundColor: '#111c2e',
        textColor: '#e2e8f0',
        borderRadius: 12,
        padding: 0,
        stripeRows: true,
        rowAlternateColor: '#101a2c',
        searchBarBackground: '#111c2e',
        searchBarTextColor: '#cbd5e1',
        searchBarBorderColor: '#1e293b',
      },
      data: {
        searchable: true,
        pagination: true,
        columns: [
          { name: 'ID',       fieldKey: 'id' },
          { name: 'Name',     fieldKey: 'name' },
          { name: 'Category', fieldKey: 'category' },
          { name: 'Price',    fieldKey: 'price' },
          { name: 'Stock',    fieldKey: 'stock' },
          { name: 'Status',   fieldKey: 'status' },
          { name: 'Sales',    fieldKey: 'sales' },
        ],
        dbBinding: '{{queries.get-products.data.data}}',
        mockValue: [],
      },
    },
    {
      id: 'node-graph-resources',
      type: 'NodeGraph',
      label: 'Resource Relationships',
      layout: { x: 8, y: 25, w: 4, h: 8 },
      style: {
        backgroundColor: '#0d1424',
        borderColor: '#22d3ee',
        borderWidth: 1,
        textColor: '#e2e8f0',
        borderRadius: 12,
        padding: 0,
        boxShadow: '0 4px 12px rgba(34, 211, 238, 0.12)',
      },
      data: {
        mockValue: {
          nodes: [
            { id: 'users',    label: '👥 Users' },
            { id: 'orders',   label: '🧾 Orders' },
            { id: 'products', label: '📦 Products' },
            { id: 'logs',     label: '📜 Logs' },
          ],
          edges: [
            { source: 'users',    target: 'orders',   label: 'places' },
            { source: 'orders',   target: 'products', label: 'contains' },
            { source: 'users',    target: 'logs',     label: 'generates' },
            { source: 'orders',   target: 'logs',     label: 'tracked' },
          ],
        },
      },
    },

    // ─── Section: Activity Logs ─────────────────────────────────────────
    {
      id: 'section-activity',
      type: 'Text',
      label: 'Activity Section',
      layout: { x: 0, y: 33, w: 12, h: 1 },
      style: {
        fontSize: 14,
        fontWeight: 600,
        textColor: '#94a3b8',
        backgroundColor: 'transparent',
        textTransform: 'uppercase',
        letterSpacing: 2,
      },
      data: { mockValue: '🔔  Activity & Logs' },
    },
    {
      id: 'logs-viewer',
      type: 'LogsViewer',
      label: 'Recent Activity',
      layout: { x: 0, y: 34, w: 12, h: 6 },
      style: {
        backgroundColor: '#0d1424',
        borderColor: '#1e293b',
        borderWidth: 1,
        borderRadius: 12,
        padding: 12,
        textColor: '#cbd5e1',
        fontFamily: 'Fira Code',
        fontSize: 12,
        levelColors: {
          INFO:  '#22d3ee',
          WARN:  '#fbbf24',
          ERROR: '#ef4444',
          DEBUG: '#94a3b8',
        },
      },
      data: {
        levelFilter: 'all',
        logSearchable: true,
        autoScroll: true,
        wrapLines: true,
        maxLines: 200,
        timestampField: 'timestamp',
        levelField: 'level',
        messageField: 'message',
        dbBinding: '{{queries.get-logs.data}}',
        mockValue: [],
      },
    },

    // ─── Section: Global Search ─────────────────────────────────────────
    {
      id: 'section-search',
      type: 'Text',
      label: 'Search Section',
      layout: { x: 0, y: 40, w: 12, h: 1 },
      style: {
        fontSize: 14,
        fontWeight: 600,
        textColor: '#94a3b8',
        backgroundColor: 'transparent',
        textTransform: 'uppercase',
        letterSpacing: 2,
      },
      data: { mockValue: '🔍  Global Search' },
    },
    {
      id: 'search-input',
      type: 'TextInput',
      label: 'Search Query',
      layout: { x: 0, y: 41, w: 9, h: 2 },
      style: {
        backgroundColor: '#111c2e',
        borderColor: '#1e293b',
        borderWidth: 1,
        borderRadius: 10,
        padding: 12,
        textColor: '#e2e8f0',
        fontSize: 14,
        focusBorderColor: '#3b82f6',
      },
      data: {
        placeholder: '🔎  Search users, orders, or products…',
        type: 'Search',
        mockValue: '',
      },
    },
    {
      id: 'search-button',
      type: 'Button',
      label: '🔎 Search',
      layout: { x: 9, y: 41, w: 3, h: 2 },
      style: {
        backgroundColor: '#3b82f6',
        borderColor: '#3b82f6',
        textColor: '#ffffff',
        borderRadius: 10,
        padding: 12,
        fontWeight: 600,
        hoverBackgroundColor: '#2563eb',
        boxShadow: '0 4px 12px rgba(59, 130, 246, 0.25)',
      },
      data: {
        dbBinding: 'queries.run-search.trigger',
        loadingState: true,
      },
    },
    {
      id: 'table-search-results',
      type: 'Table',
      label: 'Search Results',
      layout: { x: 0, y: 43, w: 12, h: 6 },
      style: {
        backgroundColor: '#0d1424',
        borderColor: '#1e293b',
        headerBackgroundColor: '#111c2e',
        textColor: '#e2e8f0',
        borderRadius: 12,
        padding: 0,
        stripeRows: true,
        rowAlternateColor: '#101a2c',
      },
      data: {
        searchable: false,
        pagination: true,
        columns: [
          { name: 'Type',    fieldKey: 'type' },
          { name: 'ID',      fieldKey: 'id' },
          { name: 'Name',    fieldKey: 'name' },
          { name: 'Details', fieldKey: 'details' },
        ],
        dbBinding: '{{queries.run-search.data}}',
        mockValue: [],
      },
    },
  ],

  queries: [
    {
      name: 'get-stats',
      resource: RESOURCE,
      endpoint: '/api/stats',
      method: 'GET',
      trigger: 'onLoad',
    },
    {
      name: 'get-revenue-chart',
      resource: RESOURCE,
      endpoint: '/api/revenue/chart',
      method: 'GET',
      trigger: 'onLoad',
    },
    {
      name: 'get-users',
      resource: RESOURCE,
      endpoint: '/api/users',
      method: 'GET',
      trigger: 'onLoad',
    },
    {
      name: 'get-orders',
      resource: RESOURCE,
      endpoint: '/api/orders',
      method: 'GET',
      trigger: 'onLoad',
    },
    {
      name: 'get-products',
      resource: RESOURCE,
      endpoint: '/api/products',
      method: 'GET',
      trigger: 'onLoad',
    },
    {
      name: 'get-logs',
      resource: RESOURCE,
      endpoint: '/api/logs',
      method: 'GET',
      trigger: 'onLoad',
    },
    {
      name: 'run-search',
      resource: RESOURCE,
      endpoint: '/api/search',
      method: 'GET',
      trigger: 'manual',
      params: {
        q: '{{componentState.search-input.value}}',
      },
      responseTransformer:
        "return [" +
        "  ...(data.users || []).map(u => ({ type: '👤 User', id: u.id, name: u.name, details: u.email })),"  +
        "  ...(data.orders || []).map(o => ({ type: '🧾 Order', id: o.id, name: o.product, details: 'Amount: $' + o.amount + ' • ' + o.status })),"  +
        "  ...(data.products || []).map(p => ({ type: '📦 Product', id: p.id, name: p.name, details: p.category + ' • $' + p.price }))"  +
        "];",
    },
  ] as any,

  canvasStyle: {
    backgroundColor: '#05080f',
    backgroundGradient: {
      enabled: true,
      direction: 135,
      stops: [
        { color: '#03060c', position: 0 },
        { color: '#0a1628', position: 100 },
      ],
    },
  },
};

export default demoBackendSuite;
