import type { TemplateConfig } from '../types/template';

const oceanicTeal: TemplateConfig = {
  id: 'oceanic-teal',
  name: 'Oceanic Teal',
  description: 'Deep ocean teal theme with vibrant cyan and white accents',
  components: [
    {
      id: 'header-container',
      type: 'Container',
      label: 'Header Section',
      layout: { x: 0, y: 0, w: 12, h: 3 },
      style: {
        backgroundColor: '#0a3d48',
        borderColor: '#00d4ff',
        borderWidth: 0,
        borderRadius: 0,
        padding: 20,
        boxShadow: '0 4px 12px rgba(0, 212, 255, 0.1)',
      },
      data: {},
    },
    {
      id: 'title-main',
      type: 'Text',
      label: 'Main Title',
      layout: { x: 0, y: 0, w: 8, h: 3 },
      style: {
        fontSize: 32,
        fontWeight: 700,
        textColor: '#00d4ff',
        backgroundColor: 'transparent',
      },
      data: { mockValue: 'Ocean Dashboard' },
    },
    {
      id: 'status-badge',
      type: 'StatusBadge',
      label: 'System Status',
      layout: { x: 10, y: 0, w: 2, h: 3 },
      style: {
        backgroundColor: '#e8f4f8',
        borderLeftColor: '#00d4ff',
        borderRadius: 10,
        padding: 12,
        textColor: '#0a3d48',
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 12px rgba(15, 23, 42, 0.06)',
      },
      data: { mockValue: '✓ Active' },
    },
    {
      id: 'card-metrics',
      type: 'StatCard',
      label: 'Total Metrics',
      layout: { x: 0, y: 3, w: 3, h: 5 },
      style: {
        backgroundColor: '#e8f4f8',
        borderLeftColor: '#00d4ff',
        borderLeftWidth: 4,
        borderRadius: 14,
        padding: 22,
        textColor: '#0a3d48',
        metricFontSize: 32,
        labelFontSize: 13,
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 12px rgba(15, 23, 42, 0.06)',
      },
      data: { mockValue: '15.2K' },
    },
    {
      id: 'card-uptime',
      type: 'StatCard',
      label: 'Uptime %',
      layout: { x: 3, y: 3, w: 3, h: 5 },
      style: {
        backgroundColor: '#e8f4f8',
        borderLeftColor: '#06b6d4',
        borderLeftWidth: 4,
        borderRadius: 14,
        padding: 22,
        textColor: '#0a3d48',
        metricFontSize: 32,
        labelFontSize: 13,
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 12px rgba(15, 23, 42, 0.06)',
      },
      data: { mockValue: '99.9%' },
    },
    {
      id: 'card-latency',
      type: 'StatCard',
      label: 'Avg Latency',
      layout: { x: 6, y: 3, w: 3, h: 5 },
      style: {
        backgroundColor: '#e8f4f8',
        borderLeftColor: '#0891b2',
        borderLeftWidth: 4,
        borderRadius: 14,
        padding: 22,
        textColor: '#0a3d48',
        metricFontSize: 32,
        labelFontSize: 13,
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 12px rgba(15, 23, 42, 0.06)',
      },
      data: { mockValue: '42ms' },
    },
    {
      id: 'card-requests',
      type: 'StatCard',
      label: 'Requests/s',
      layout: { x: 9, y: 3, w: 3, h: 5 },
      style: {
        backgroundColor: '#e8f4f8',
        borderLeftColor: '#00d4ff',
        borderLeftWidth: 4,
        borderRadius: 14,
        padding: 22,
        textColor: '#0a3d48',
        metricFontSize: 32,
        labelFontSize: 13,
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 12px rgba(15, 23, 42, 0.06)',
      },
      data: { mockValue: '2.8K' },
    },
    {
      id: 'chart-performance',
      type: 'LineChart',
      label: 'Performance Over Time',
      layout: { x: 0, y: 8, w: 6, h: 8 },
      style: {
        backgroundColor: '#e8f4f8',
        borderColor: '#b0e0e6',
        borderRadius: 12,
        padding: 18,
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 12px rgba(15, 23, 42, 0.06)',
      },
      data: {
        showGrid: true,
        showLegend: true,
        smooth: true,
      },
    },
    {
      id: 'chart-distribution',
      type: 'BarChart',
      label: 'Resource Distribution',
      layout: { x: 6, y: 8, w: 6, h: 8 },
      style: {
        backgroundColor: '#e8f4f8',
        borderColor: '#b0e0e6',
        borderRadius: 12,
        padding: 18,
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 12px rgba(15, 23, 42, 0.06)',
      },
      data: {
        showGrid: true,
        showLegend: true,
      },
    },
    {
      id: 'logs-viewer',
      type: 'LogsViewer',
      label: 'System Logs',
      layout: { x: 0, y: 16, w: 12, h: 5 },
      style: {
        backgroundColor: '#0d1424',
        borderColor: '#1e2d42',
        borderRadius: 12,
        padding: 16,
        fontFamily: 'Fira Code',
        fontSize: 12,
        lineHeight: 1.6,
        textColor: '#e2e8f0',
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 12px rgba(15, 23, 42, 0.06)',
      },
      data: {},
    },
  ],
  queries: [],
  canvasStyle: {
    backgroundColor: '#081a20',
    backgroundGradient: {
      enabled: true,
      direction: 135,
      stops: [
        { color: '#051019', position: 0 },
        { color: '#0a3d48', position: 100 },
      ],
    },
  },
};

export default oceanicTeal;
