import type { TemplateConfig } from '../types/template';

const projectOverview: TemplateConfig = {
  id: 'project-overview',
  name: 'Project Overview',
  description: 'KPI stat cards, monthly spend bar chart, and project summary table',
  components: [
    {
      id: 'stat-1',
      type: 'StatCard',
      label: 'Total Budget',
      style: {
        backgroundColor: '#ffffff',
        textColor: '#0f1117',
        fontFamily: 'Inter',
        fontSize: 14,
        borderRadius: 10,
        borderColor: '#e3e6ec',
        borderWidth: 1,
        padding: 20,
      },
      data: {
        fieldName: 'budget_total',
        mockValue: '₹4,20,000',
        dbBinding: 'projects.budget_total',
        refreshOn: 'onLoad',
      },
    },
    {
      id: 'stat-2',
      type: 'StatCard',
      label: 'Active Projects',
      style: {
        backgroundColor: '#ffffff',
        textColor: '#0f1117',
        fontFamily: 'Inter',
        fontSize: 14,
        borderRadius: 10,
        borderColor: '#e3e6ec',
        borderWidth: 1,
        padding: 20,
      },
      data: {
        fieldName: 'active_projects',
        mockValue: '12',
        dbBinding: 'projects.active_count',
        refreshOn: 'onLoad',
      },
    },
    {
      id: 'stat-3',
      type: 'StatCard',
      label: 'Completion Rate',
      style: {
        backgroundColor: '#ffffff',
        textColor: '#0f1117',
        fontFamily: 'Inter',
        fontSize: 14,
        borderRadius: 10,
        borderColor: '#e3e6ec',
        borderWidth: 1,
        padding: 20,
      },
      data: {
        fieldName: 'completion_rate',
        mockValue: '78%',
        dbBinding: 'projects.completion_rate',
        refreshOn: 'onLoad',
      },
    },
    {
      id: 'stat-4',
      type: 'StatCard',
      label: 'Team Members',
      style: {
        backgroundColor: '#ffffff',
        textColor: '#0f1117',
        fontFamily: 'Inter',
        fontSize: 14,
        borderRadius: 10,
        borderColor: '#e3e6ec',
        borderWidth: 1,
        padding: 20,
      },
      data: {
        fieldName: 'team_count',
        mockValue: '34',
        dbBinding: 'projects.team_count',
        refreshOn: 'onLoad',
      },
    },
    {
      id: 'chart-1',
      type: 'BarChart',
      label: 'Monthly Spend',
      style: {
        backgroundColor: '#ffffff',
        textColor: '#0f1117',
        fontFamily: 'Inter',
        fontSize: 14,
        borderRadius: 10,
        borderColor: '#e3e6ec',
        borderWidth: 1,
        padding: 20,
      },
      data: {
        series: [{ name: 'Spend', fieldKey: 'spend' }],
        mockValue: [
          { month: 'Jan', spend: 32000 },
          { month: 'Feb', spend: 45000 },
          { month: 'Mar', spend: 38000 },
          { month: 'Apr', spend: 52000 },
          { month: 'May', spend: 41000 },
          { month: 'Jun', spend: 48000 },
        ],
        dbBinding: 'projects.monthly_spend',
        refreshOn: 'onLoad',
      },
    },
    {
      id: 'table-1',
      type: 'Table',
      label: 'Project Summary',
      style: {
        backgroundColor: '#ffffff',
        textColor: '#0f1117',
        fontFamily: 'Inter',
        fontSize: 13,
        borderRadius: 10,
        borderColor: '#e3e6ec',
        borderWidth: 1,
        padding: 0,
      },
      data: {
        columns: [
          { name: 'Project', fieldKey: 'project' },
          { name: 'Owner', fieldKey: 'owner' },
          { name: 'Budget', fieldKey: 'budget' },
          { name: 'Status', fieldKey: 'status' },
        ],
        mockValue: [
          { project: 'Website Redesign', owner: 'Alice', budget: '₹1,20,000', status: 'In Progress' },
          { project: 'Mobile App v2', owner: 'Bob', budget: '₹85,000', status: 'Planning' },
          { project: 'API Migration', owner: 'Charlie', budget: '₹62,000', status: 'Completed' },
          { project: 'Data Pipeline', owner: 'Diana', budget: '₹95,000', status: 'In Progress' },
          { project: 'Auth Service', owner: 'Eve', budget: '₹58,000', status: 'Review' },
        ],
        dbBinding: 'projects.summary',
        refreshOn: 'onLoad',
      },
    },
  ],
};

export default projectOverview;
